[tools]
python = "3.14"
node = "lts"
"npm:@salesforce/cli" = "latest"

[tasks.install]
description = "Install Python dependencies"
run = "python -m ensurepip --upgrade > /dev/null 2>&1 && python -m pip install -q -r requirements.txt"

[tasks.download]
description = "Uruchomienie pobierania załączników Salesforce (konfiguracja z .env)"
run = "python main.py"

[tasks.run-debug]
description = "Uruchomienie z debug output"
run = "python main.py --debug"
