"""
Query Executor Module

Handles execution of SOQL queries via Salesforce CLI bash scripts.
"""

import subprocess
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def run_query_script_with_filter(
    org_alias: str,
    output_dir: Path,
    where_clause: str
) -> Path:
    """
    Run the bash script to query attachments with a WHERE clause filter.

    This function is used by the CSV-records workflow to query attachments
    for specific ParentIds using a pre-built WHERE clause (e.g., WHERE ParentId IN (...)).

    Args:
        org_alias: Salesforce org alias
        output_dir: Directory to save metadata CSV
        where_clause: Pre-built WHERE clause (e.g., "WHERE ParentId IN ('id1','id2')")

    Returns:
        Path to the generated CSV file

    Raises:
        RuntimeError: If query script fails
        FileNotFoundError: If script or CSV not found
    """
    logger.info("Running attachment query script with filter...")
    logger.debug(f"WHERE clause: {where_clause[:100]}...")  # Log first 100 chars

    script_path = Path(__file__).parent.parent.parent / 'scripts' / 'query_attachments.sh'

    if not script_path.exists():
        raise FileNotFoundError(
            f"Query script not found at path: {script_path.absolute()}. "
            f"Please ensure the scripts directory and query_attachments.sh exist."
        )

    # Run script with WHERE clause as 3rd parameter
    # Parameters: org_alias, output_dir, where_clause
    result = subprocess.run(
        ['bash', str(script_path), org_alias, str(output_dir), where_clause],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        logger.error(f"Query script failed: {result.stderr}")
        raise RuntimeError("Failed to query attachments with filter")

    logger.info(result.stdout)

    # Find the generated CSV file (most recent in output_dir)
    csv_files = sorted(output_dir.glob('attachments_*.csv'), key=lambda p: p.stat().st_mtime)

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV file generated by query script in directory: {output_dir.absolute()}. "
            f"The query script may have failed or no attachments were found."
        )

    return csv_files[-1]  # Return most recent
